# Generated by Django 2.0.1 on 2018-01-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0004_auto_20180113_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('title',), 'verbose_name': 'Альбом', 'verbose_name_plural': 'Альбомы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('genre',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ('name',), 'verbose_name': 'Исполнитель', 'verbose_name_plural': 'Исполнители'},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ('song',), 'verbose_name': 'Песня', 'verbose_name_plural': 'Песни'},
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(related_name='tracks', to='djapp.Album'),
        ),
    ]
