# Generated by Django 2.0.1 on 2018-01-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djapp', '0005_auto_20180113_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Выпущен'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(related_name='Album_by_genre', to='djapp.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre',
            field=models.CharField(max_length=30, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ManyToManyField(related_name='tracks', to='djapp.Album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='track',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='track',
            name='song',
            field=models.CharField(max_length=30, verbose_name='Песня'),
        ),
    ]
